project:
  type: book
  output-dir: docs

book:
  title: "Reinforcement Learning"
  author: "Rohan Gala"
  date: "10/30/2022"
  chapters:
    - index.qmd
    - 00_intro.qmd
    - 01_fundamentals.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt